-- MySQL Script generated by MySQL Workbench
-- Sun Feb 27 23:02:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sisinv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisinv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisinv` DEFAULT CHARACTER SET utf8 ;
USE `sisinv` ;

-- -----------------------------------------------------
-- Table `sisinv`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisinv`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `nombre_Proveedor` VARCHAR(45) NOT NULL,
  `telefono_Proveedor` INT(10) NOT NULL,
  `telefono2_Proveedor` INT(10) NOT NULL,
  `direccion_Proveedor` VARCHAR(45) NOT NULL,
  `email_Proveedor` VARCHAR(45) NOT NULL,
  `descripcion_Proveedor` VARCHAR(45) NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisinv`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisinv`.`Rol` (
  `idRol` INT NOT NULL,
  `nombre_Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisinv`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisinv`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `identidad_Usuario` VARCHAR(45) NOT NULL,
  `contra_Usuario` VARCHAR(45) NOT NULL,
  `nombres_Usuario` VARCHAR(45) NOT NULL,
  `apellido1_Usuario` VARCHAR(45) NOT NULL,
  `apellido2_Usuario` VARCHAR(45) NOT NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Rol_idx` (`idRol` ASC),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  CONSTRAINT `fk_Usuario_Rol`
    FOREIGN KEY (`idRol`)
    REFERENCES `sisinv`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisinv`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisinv`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nombre_Cliente` VARCHAR(45) NOT NULL,
  `apellido_Cliente` VARCHAR(45) NOT NULL,
  `apellido2_Cliente` VARCHAR(45) NOT NULL,
  `telefono_Cliente` INT(10) NOT NULL,
  `email_Cliente` VARCHAR(45) NOT NULL,
  `direccion_Cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisinv`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisinv`.`Producto` (
  `idProducto` INT NOT NULL,
  `nom_Producto` VARCHAR(45) NOT NULL,
  `descripcion_Producto` VARCHAR(45) NULL,
  `precio_Producto` DECIMAL(10) NOT NULL,
  `precio_sugerido` DECIMAL(10) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisinv`.`Entradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisinv`.`Entradas` (
  `idEntradas` INT NOT NULL AUTO_INCREMENT,
  `codigo_Entrada` INT NOT NULL,
  `fecha_Entrada` DATE NOT NULL,
  `cantidad_Entrada` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  PRIMARY KEY (`idEntradas`),
  INDEX `fk_Entradas_Proveedor_idx` (`idProveedor` ASC),
  INDEX `fk_Entradas_Producto1_idx` (`codigo_Entrada` ASC),
  CONSTRAINT `fk_Entradas_Proveedor`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `sisinv`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entradas_Producto1`
    FOREIGN KEY (`codigo_Entrada`)
    REFERENCES `sisinv`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisinv`.`Salidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisinv`.`Salidas` (
  `idSalidas` INT NOT NULL AUTO_INCREMENT,
  `codigo_Salida` INT NOT NULL,
  `fecha_Salida` DATE NOT NULL,
  `cantidad_Salida` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idSalidas`),
  INDEX `fk_Salidas_Cliente1_idx` (`idCliente` ASC),
  INDEX `fk_Salidas_Producto1_idx` (`codigo_Salida` ASC),
  CONSTRAINT `fk_Salidas_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `sisinv`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salidas_Producto1`
    FOREIGN KEY (`codigo_Salida`)
    REFERENCES `sisinv`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisinv`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisinv`.`Inventario` (
  `idInventario` INT NOT NULL AUTO_INCREMENT,
  `codigo_Inventario` INT NOT NULL,
  `entrada_Inventario` INT NOT NULL,
  `cantidad_Salida` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `fk_Inventario_Producto1_idx` (`codigo_Inventario` ASC),
  CONSTRAINT `fk_Inventario_Producto1`
    FOREIGN KEY (`codigo_Inventario`)
    REFERENCES `sisinv`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
